// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NebbAir.Data;

namespace NebbAir.Migrations
{
    [DbContext(typeof(NebbAirContext))]
    partial class NebbAirContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NebbAir.Models.Patnici", b =>
                {
                    b.Property<int>("PatnikID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarryOn");

                    b.Property<int>("CheckIn");

                    b.Property<DateTime>("DataNaRagjanje");

                    b.Property<DateTime>("Departure");

                    b.Property<string>("Destination")
                        .IsRequired();

                    b.Property<string>("FlightNo")
                        .IsRequired();

                    b.Property<string>("Ime")
                        .IsRequired();

                    b.Property<string>("Origin")
                        .IsRequired();

                    b.Property<string>("PassporNo")
                        .IsRequired();

                    b.Property<string>("Prezime")
                        .IsRequired();

                    b.Property<DateTime>("Return");

                    b.Property<int>("Trolley");

                    b.HasKey("PatnikID");

                    b.ToTable("Patnici");
                });
#pragma warning restore 612, 618
        }
    }
}
